### ISSUE TITLE
libicui18n.so.55 missing

### ISSUE THREAD

**Issue by probonopd** [foxoman/pdftoword#1]
```
$ '/home/me/Downloads/PdftoWord-x86_64.AppImage' 
/home/me/Downloads/PdftoWord-x86_64.AppImage: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory
```

Please include `libicui18n.so.55` in the AppImage.

**Comment by foxoman** [comment]
@probonopd  thank you for reporting this, I have repackage with Qt 5.11 which based on libicui18n.so.56 and it's included in the final image, kindly check
